apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rtview-dataserver-sp
  name: rtview-dataserver-sp
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: grahamea/test2:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
